services:
  explore:
    build:
      context: .
      dockerfile: explore-service/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgres://postgres:admin@db/explore?sslmode=disable
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: explore_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: explore
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data   # Persistent data storage

volumes:
  data_sql: